package com.example.tijo.movies_proj;

/**
 * Created by tijoj on 2/3/2018.
 */

public class stuffToDo {

    //TODO: UPDATE THE LAYOUT TO MAKE THE USER RATING AND ADD TIME TO BE PROPERLY ALLIGNED

    //TODO: UPDATE THE LAYOUT TO INCLUDE TRAILERS

    //TODO: ADD THE TRAILERS PART TO THE MOVIE DETAILS PAGE

    //TODO: UNDER THE TRAILER ADD THE REVIEWS MAKE IT WITH FAKE DATA

    //TODO: CREATE ONCLICK ON TRAILER ELEMENT TO OPEN INTENT FOR YOUTUBE

    // TODO: HOOK UP WITH API AND LETS DOWNLOAD STUFF

    // TODO: CREATE SQL DATABASE AND ADD THE MOVIE DATABASE ELEMENTS

    // TODO: CREATE A CONTENT PROVIDER WHICH STORES ALL THE DATA

    // TODO: ADD A FAVORITES BUTTON ON THE LAYOUT

    // TODO: HOOK UP FAVORITES BUTTON TO THE CONTENT PROVIDER

    // TODO: CHECK TO SEE IF FAKE DATA CAN BE ADDED

    // TODO: CHECK TO SEE IF FAKE DATA CAN BE DELETED ON BUTTON PRESS

    // TODO: HOOK UP BUTTON ON THE SETTINGS LAYOUT TO SHOW ONLY FAVORITED MOVIES

    // TODO: CONFIRM IT SHOUWS OFF LINE TOO ONLY THE FAVORITED ONES

    // TODO: HOOK UP API TO DATA

    // TODO: REVIEW ALL LAYOUT AND ADD THE LAYOUT FILES AND OTHER STUFF TO RES FILES

    // TODO: IMPLEMETN SHARE FUNCTIONALITY ON THE DETAILS SCREEN

    // TODO: REVIEW PROJECT AND COMMENT IT

    // TODO: FLINT IT AND CLEAN AND SUBMIT
}
